In [1]:
import os
os.chdir("../")
print(os.getcwd())

c:\Users\Amrit\Intilt\Intrade_ai

In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import datetime
import json

from utils.data_cleaning import get_missing_data_dates, get_continuous_1min_data

In [7]:
import boto3
import pandas as pd

# Creating the low level functional client
client = boto3.client(
    's3',
    aws_access_key_id = 'AKIARJFZWD4TKOK4T2VO',
    aws_secret_access_key = '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',
    region_name = 'ap-south-1'
)

In [8]:
with open('config/config_cleaning.json', 'r') as openfile:
    config_cleaning = json.load(openfile)

In [29]:
# Create the S3 object
obj = client.get_object(
    Bucket = 'intrade-dev-data',
    Key = config_cleaning['file_paths']['nifty_1min']
)
data = pd.read_csv(obj['Body'])

In [30]:
data

               date      time     open     high      low    close
0        2008-01-01  09:55:00  6138.60  6154.60  6138.60  6148.90
1        2008-01-01  09:56:00  6149.75  6149.75  6132.80  6132.80
2        2008-01-01  09:57:00  6138.25  6138.25  6127.95  6127.95
3        2008-01-01  09:58:00  6127.15  6127.15  6120.90  6120.90
4        2008-01-01  09:59:00  6118.05  6118.05  6113.55  6113.90
...             ...       ...      ...      ...      ...      ...
1348612  2007-12-31  15:26:00  6131.25  6133.90  6130.45  6133.60
1348613  2007-12-31  15:27:00  6133.65  6133.65  6131.30  6131.30
1348614  2007-12-31  15:28:00  6131.90  6131.90  6128.80  6128.80
1348615  2007-12-31  15:29:00  6127.00  6129.00  6126.40  6127.40
1348616  2007-12-31  15:30:00  6126.50  6126.50  6126.50  6126.50

[1348617 rows x 6 columns]

In [36]:
nifty_daily_continous = get_continuous_1min_data("Nifty",data)

EmptyDataError: No columns to parse from file

In [35]:
holidays_file = client.get_object(
        Bucket = 'intrade-dev-data',
        Key = config_cleaning['file_paths']['holidays_file']
    )
holidays = pd.read_csv(holidays_file['Body'])
holidays

           date        day           description
0    2007-01-01     Monday              Bakri ID
1    2007-01-26     Friday          Republic Day
2    2007-01-30    Tuesday              Moharram
3    2007-02-16     Friday         Mahashivratri
4    2007-03-27    Tuesday            Ram Navami
..          ...        ...                   ...
229  2022-08-15     Monday      Independence Day
230  2022-08-31  Wednesday      Ganesh Chaturthi
231  2022-10-05  Wednesday              Dussehra
232  2022-10-24     Monday    Diwali-Laxmi Pujan
233  2022-10-26  Wednesday  Diwali-Balipratipada

[234 rows x 3 columns]